"""
Issue planner — turns a GitHub issue into a minimal, precise implementation plan.

Acts as a senior software architect: given the issue, repo structure, and tech
stack it returns exact files to change, specific logic updates, edge cases, and
required tests.

OUTPUT SCHEMA (strict):
{
  "plan": [
    { "step": 1, "description": "...", "files": ["..."] }
  ],
  "edge_cases": ["..."],
  "tests_needed": ["..."]
}
"""

import json
import logging
from dataclasses import dataclass, field

import anthropic

log = logging.getLogger(__name__)

_SYSTEM = """\
You are a senior software architect planning the implementation of a GitHub issue
for an autonomous coding agent.

Your plan must be:
- Minimal — only touch what is necessary to fix the issue
- Precise — name exact files, functions, and logic changes
- Complete — cover edge cases and required tests

Rules:
- Do not describe "how to think about it" — describe exactly what to change
- File paths must match the actual repo structure provided
- Steps must be in dependency order (read-before-write, dependencies first)
- Each step should change one cohesive concern, not a grab-bag of edits
- If the issue is a bug, identify the root cause file first
- If the issue is a feature, identify the entry point and ripple outward

Respond with ONLY valid JSON — no markdown, no commentary, no extra fields:
{
  "plan": [
    { "step": 1, "description": "<specific action>", "files": ["<exact/path.ext>"] }
  ],
  "edge_cases": ["<concrete scenario that could break the fix>"],
  "tests_needed": ["<specific test case description>"]
}
"""

_USER_TEMPLATE = """\
## INPUT:
- Issue title: {issue_title}
- Issue summary: {summary}
- Repo structure:
{file_tree}
- Tech stack: {tech_stack}

## TASK:
Create a minimal, precise plan. Include exact files to change, specific logic
updates, any new functions/components, edge cases, and required tests.
"""


# ---------------------------------------------------------------------------
# Result dataclasses
# ---------------------------------------------------------------------------


@dataclass
class PlanStep:
    step: int
    description: str
    files: list[str]


@dataclass
class IssuePlan:
    steps: list[PlanStep]
    edge_cases: list[str]
    tests_needed: list[str]

    @property
    def all_files(self) -> list[str]:
        """Flat, deduplicated list of every file mentioned in the plan."""
        seen: set[str] = set()
        result: list[str] = []
        for s in self.steps:
            for f in s.files:
                if f not in seen:
                    seen.add(f)
                    result.append(f)
        return result

    def to_solver_context(self) -> str:
        """
        Compact text block to inject into the solver's system prompt.
        Tells Claude exactly what to read and change.
        """
        lines = ["## Implementation plan (generated by architect)\n"]
        for s in self.steps:
            files_str = ", ".join(s.files) if s.files else "—"
            lines.append(f"Step {s.step}: {s.description}")
            lines.append(f"  Files: {files_str}")
        if self.edge_cases:
            lines.append("\nEdge cases to handle:")
            for ec in self.edge_cases:
                lines.append(f"  - {ec}")
        if self.tests_needed:
            lines.append("\nTests to add:")
            for t in self.tests_needed:
                lines.append(f"  - {t}")
        return "\n".join(lines)

    @classmethod
    def empty(cls) -> "IssuePlan":
        return cls(steps=[], edge_cases=[], tests_needed=[])


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------


class IssuePlanner:
    """
    Generates a structured implementation plan from an issue + repo context.
    Uses claude-sonnet-4-6 for architect-quality reasoning at moderate cost.
    """

    def __init__(self, anthropic_api_key: str):
        self._client = anthropic.Anthropic(api_key=anthropic_api_key)

    def plan(
        self,
        issue_title: str,
        issue_body: str,
        file_tree: str,
        tech_stack: str,
    ) -> IssuePlan:
        """
        Return an IssuePlan. Falls back to IssuePlan.empty() on any error so
        the solver can still run without a plan.
        """
        summary = _summarise(issue_body)

        user_message = _USER_TEMPLATE.format(
            issue_title=issue_title,
            summary=summary,
            file_tree=file_tree or "(unavailable)",
            tech_stack=tech_stack or "unknown",
        )

        try:
            response = self._client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=2048,
                system=_SYSTEM,
                messages=[{"role": "user", "content": user_message}],
            )
        except Exception as exc:
            log.error("Planner API call failed: %s", exc)
            return IssuePlan.empty()

        raw = response.content[0].text.strip()

        # Strip accidental markdown fences.
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        try:
            data = json.loads(raw)
        except json.JSONDecodeError as exc:
            log.warning("Planner returned non-JSON: %s  raw=%r", exc, raw)
            return IssuePlan.empty()

        return _parse_plan(data)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _summarise(body: str, max_chars: int = 600) -> str:
    """Return the first *max_chars* characters of the issue body."""
    body = (body or "").strip()
    if len(body) <= max_chars:
        return body
    return body[:max_chars].rsplit(" ", 1)[0] + " …"


def _parse_plan(data: dict) -> IssuePlan:
    """Parse the raw JSON dict into an IssuePlan, with safe defaults."""
    try:
        steps = [
            PlanStep(
                step=int(s.get("step", i + 1)),
                description=str(s.get("description", "")),
                files=[str(f) for f in s.get("files", [])],
            )
            for i, s in enumerate(data.get("plan", []))
        ]
        edge_cases = [str(e) for e in data.get("edge_cases", [])]
        tests_needed = [str(t) for t in data.get("tests_needed", [])]
        return IssuePlan(steps=steps, edge_cases=edge_cases, tests_needed=tests_needed)
    except (TypeError, ValueError) as exc:
        log.warning("Failed to parse plan: %s  data=%r", exc, data)
        return IssuePlan.empty()
